2025-02-17/myapp/main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    # path("users/", views.UsersView.as_view(), name="users"),
    path("users/", views.users, name="users"),
    path("<int:pk>/", views.DetailsView.as_view(), name="details"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

2025-02-17/myapp/myapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
]

2025-02-17/myapp/main/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=255)
    published_date = models.DateTimeField(
        "date published"
    )  # to give a human-readable name,optional params

    def __str__(self):
        return self.question_text
        # this returns the text when accessing the objects through django-admin or python-shell

    def was_published_recently(self):
        return self.published_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

2025-02-17/myapp/main/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question, User

# def index(request):
#     # orders by recent first and only shows the first 5 items
#     latest_question_list = Question.objects.order_by("-published_date")[:5]
#     context = {"latest_question_list": latest_question_list}
#     return render(request, "main/index.html", context)


# def details(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, "main/details.html", {"question": question})


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "main/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "main/detail.html",
            {"question": question, "error_message": "You didn't select a choice"},
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # args expects a tuple so, we have to put ',' even if there is one element
        # reverse is used to redirect to a view without hardcoding the url
        return HttpResponseRedirect(reverse("main:results", args=(question.id,)))


class IndexView(generic.ListView):
    template_name = "main/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-published_date")[:5]


class DetailsView(generic.DetailView):
    model = Question
    template_name = "main/details.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "main/results.html"


# easy way to do it
# class UsersView(generic.ListView):
#     model = User
#     template_name = "main/users.html"
#     context_object_name = "users"


# Function based
def users(request):
    users = User.objects.all()
    return render(request, "main/users.html", context={"users": users})

2025-02-17/myapp/main/templates/main/details.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title></title>
    <link href="css/style.css" rel="stylesheet" />
</head>

<body>
    <a href="{% url 'main:index' %}">Go to home</a>
    <form action="{% url 'main:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}
            <p>{{error_message}}</p>
            {% endif %} {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" value="{{choice.id}}" />
            <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
            <!-- It will look like -->
            <!-- choice1 -->
            <!-- choice2 -->
            <!-- choice3 -->
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote" />
    </form>
</body>

</html>

2025-02-17/myapp/main/templates/main/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title></title>
    <link href="css/style.css" rel="stylesheet" />
</head>

<body>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
            <a href="{% url 'main:details' question.id %}">{{ question.question_text }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</body>

</html>

2025-02-17/myapp/main/templates/main/results.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title></title>
    <link href="css/style.css" rel="stylesheet" />
</head>

<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>
            {{choice.choice_text}} -- {{choice.votes}}
            <span>vote{{ choice.votes|pluralize }}</span>
        </li>
        {% endfor%}
    </ul>

    <a href="{% url 'main:details' question.id %}">Vote again?</a>
</body>

</html>

2025-02-17/myapp/main/templates/main/users.html
<!DOCTYPE>
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title></title>
    <link href="css/style.css" rel="stylesheet" />
</head>

<body>
    {% if not user%}
    <p>No users found..</p>
    {% endif %}
    <h2>List of all users</h2>
    <ol>
        {% for user in users %}
        <li>
            <h2>User info</h2>
            <ul>
                <li>{{user.first_name}}</li>
                <li>{{user.last_name}}</li>
                <li>{{user.email}}</li>
            </ul>
        </li>
        {% endfor %}
    </ol>
</body>

</html>